Docentes/Models/Docente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Docentes.Models
{
    public class Docente
    {
        public int Id { get; set; }
        [DisplayName("Nombres"), Required]
        public string Nombres { get; set; }
        [DisplayName("Apellidos"), Required]
        public string Apellidos { get; set; }
        [DisplayName("No INSS"), Required]
        public string Inss { get; set; }
        [DisplayName("Imagen")]
        public string Imagen { get; set; }


        public ICollection<Proyecto> Proyectos { get; set; }
        public ICollection<Publicacion> Publicaciones { get; set; }


        public virtual string FullName
        {
            get { return $"{Nombres} {Apellidos}";  }
        }

    }
}

Docentes/Models/Proyecto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Docentes.Models
{
    public class Proyecto
    {
        public int Id { get; set; }
        [DisplayName("Nombre del proyecto"), Required]
        public string Nombre { get; set; }
        [DisplayName("Duración"), Required]
        public string Duracion { get; set; }
        [DisplayName("Patrocinador"), Required]
        public string Patrocinador { get; set; }

        [DisplayName("Docente"), Required]
        public int DocenteId { get; set; }
        public Docente Docente { get; set; }

    }
}

Docentes/Controllers/DocentesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Docentes.Models;

namespace Docentes.Controllers
{
    public class DocentesController : Controller
    {
        private DocentesContext db = new DocentesContext();
        private Random rnd = new Random();

        // GET: Docentes
        public ActionResult Index()
        {
            return View(db.Docentes.ToList());
        }

        // GET: Docentes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Docente docente = db.Docentes.Find(id);
            if (docente == null)
            {
                return HttpNotFound();
            }
            return View(docente);
        }


            // GET: Docentes/Details/5
        public ActionResult Publicaciones(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Docente docente = db.Docentes.Find(id);

            if (docente == null)
            {
                return HttpNotFound();
            }
            docente.Publicaciones = db.Publicacions.Where(x => x.DocenteId == id).ToList();
            return PartialView(docente);
        }

        public ActionResult Proyectos(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Docente docente = db.Docentes.Find(id);
            if (docente == null)
            {
                return HttpNotFound();
            }
            docente.Proyectos = db.Proyectoes.Where(x => x.DocenteId == id).ToList();
            return PartialView(docente);
        }


        // GET: Docentes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Docentes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nombres,Apellidos,Inss,Imagen")] Docente docente)
        {
            if (ModelState.IsValid)
            {

                HttpPostedFileBase fileUpload = Request.Files[0];
                if (fileUpload.ContentLength > 0)
                {
                    //var fileName = Path.GetFileName(fileUpload.FileName).Trim();
                    var fileExtension = Path.GetExtension(fileUpload.FileName);
                    var identificador = rnd.Next(1, 9999);
                    var fileName = $"{docente.GetHashCode()}{fileExtension}";
                    var path = Path.Combine(Server.MapPath("~/Files/"), $"{fileName}");
                    fileUpload.SaveAs(path);
                    docente.Imagen = fileName;
                }


                db.Docentes.Add(docente);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(docente);
        }

        // GET: Docentes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Docente docente = db.Docentes.Find(id);
            if (docente == null)
            {
                return HttpNotFound();
            }
            return View(docente);
        }

        // POST: Docentes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nombres,Apellidos,Inss")] Docente docente)
        {
            if (ModelState.IsValid)
            {

                HttpPostedFileBase fileUpload = Request.Files[0];
                if (fileUpload.ContentLength > 0)
                {
                    var fileExtension = Path.GetExtension(fileUpload.FileName);
                    var identificador = rnd.Next(1, 9999);
                    var fileName = $"{docente.GetHashCode()}{fileExtension}";
                    var path = Path.Combine(Server.MapPath("~/Files/"), $"{fileName}");
                    fileUpload.SaveAs(path);
                    docente.Imagen = fileName;
                }
                db.Entry(docente).State = EntityState.Modified;
                if (docente.Imagen == null)
                {
                    db.Entry(docente).Property("Imagen").IsModified = false;
                }
               
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(docente);
        }

        // GET: Docentes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Docente docente = db.Docentes.Find(id);
            if (docente == null)
            {
                return HttpNotFound();
            }
            return View(docente);
        }

        // POST: Docentes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Docente docente = db.Docentes.Find(id);
            db.Docentes.Remove(docente);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Docentes/Controllers/ProyectosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Docentes.Models;

namespace Docentes.Controllers
{
    public class ProyectosController : Controller
    {
        private DocentesContext db = new DocentesContext();

        // GET: Proyectos
        public ActionResult Index()
        {
            var proyectoes = db.Proyectoes.Include(p => p.Docente);
            return View(proyectoes.ToList());
        }

        // GET: Proyectos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Proyecto proyecto = db.Proyectoes.Find(id);
            if (proyecto == null)
            {
                return HttpNotFound();
            }
            return View(proyecto);
        }

        // GET: Proyectos/Create
        public ActionResult Create()
        {
            ViewBag.DocenteId = new SelectList(db.Docentes, "Id", "Nombres");
            return View();
        }

        // POST: Proyectos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nombre,Duracion,Patrocinador,DocenteId")] Proyecto proyecto)
        {
            if (ModelState.IsValid)
            {
                db.Proyectoes.Add(proyecto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DocenteId = new SelectList(db.Docentes, "Id", "Nombres", proyecto.DocenteId);
            return View(proyecto);
        }

        // GET: Proyectos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Proyecto proyecto = db.Proyectoes.Find(id);
            if (proyecto == null)
            {
                return HttpNotFound();
            }
            ViewBag.DocenteId = new SelectList(db.Docentes, "Id", "Nombres", proyecto.DocenteId);
            return View(proyecto);
        }

        // POST: Proyectos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nombre,Duracion,Patrocinador,DocenteId")] Proyecto proyecto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(proyecto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DocenteId = new SelectList(db.Docentes, "Id", "Nombres", proyecto.DocenteId);
            return View(proyecto);
        }

        // GET: Proyectos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Proyecto proyecto = db.Proyectoes.Find(id);
            if (proyecto == null)
            {
                return HttpNotFound();
            }
            return View(proyecto);
        }

        // POST: Proyectos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Proyecto proyecto = db.Proyectoes.Find(id);
            db.Proyectoes.Remove(proyecto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Docentes/Controllers/PublicacionesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Docentes.Models;

namespace Docentes.Controllers
{
    public class PublicacionesController : Controller
    {
        private DocentesContext db = new DocentesContext();

        // GET: Publicaciones
        public ActionResult Index()
        {
            var publicacions = db.Publicacions.Include(p => p.Docente).Include(p => p.Editorial).Include(p => p.Tipo);
            return View(publicacions.ToList());
        }

        // GET: Publicaciones/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Publicacion publicacion = db.Publicacions.Find(id);
            if (publicacion == null)
            {
                return HttpNotFound();
            }
            return View(publicacion);
        }

        // GET: Publicaciones/Create
        public ActionResult Create()
        {
            ViewBag.DocenteId = new SelectList(db.Docentes, "Id", "FullName");
            ViewBag.EditorialId = new SelectList(db.Editorials, "Id", "Nombre");
            ViewBag.TipoPublicacionId = new SelectList(db.TipoPublicacions, "Id", "Tipo");
            return View();
        }

        // POST: Publicaciones/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Titulo,Año,EditorialId,TipoPublicacionId,DocenteId")] Publicacion publicacion)
        {
            if (ModelState.IsValid)
            {
                db.Publicacions.Add(publicacion);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DocenteId = new SelectList(db.Docentes, "Id", "Nombres", publicacion.DocenteId);
            ViewBag.EditorialId = new SelectList(db.Editorials, "Id", "Nombre", publicacion.EditorialId);
            ViewBag.TipoPublicacionId = new SelectList(db.TipoPublicacions, "Id", "Tipo", publicacion.TipoPublicacionId);
            return View(publicacion);
        }

        // GET: Publicaciones/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Publicacion publicacion = db.Publicacions.Find(id);
            if (publicacion == null)
            {
                return HttpNotFound();
            }
            ViewBag.DocenteId = new SelectList(db.Docentes, "Id", "Nombres", publicacion.DocenteId);
            ViewBag.EditorialId = new SelectList(db.Editorials, "Id", "Nombre", publicacion.EditorialId);
            ViewBag.TipoPublicacionId = new SelectList(db.TipoPublicacions, "Id", "Tipo", publicacion.TipoPublicacionId);
            return View(publicacion);
        }

        // POST: Publicaciones/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Titulo,Año,EditorialId,TipoPublicacionId,DocenteId")] Publicacion publicacion)
        {
            if (ModelState.IsValid)
            {
                db.Entry(publicacion).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DocenteId = new SelectList(db.Docentes, "Id", "Nombres", publicacion.DocenteId);
            ViewBag.EditorialId = new SelectList(db.Editorials, "Id", "Nombre", publicacion.EditorialId);
            ViewBag.TipoPublicacionId = new SelectList(db.TipoPublicacions, "Id", "Tipo", publicacion.TipoPublicacionId);
            return View(publicacion);
        }

        // GET: Publicaciones/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Publicacion publicacion = db.Publicacions.Find(id);
            if (publicacion == null)
            {
                return HttpNotFound();
            }
            return View(publicacion);
        }

        // POST: Publicaciones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Publicacion publicacion = db.Publicacions.Find(id);
            db.Publicacions.Remove(publicacion);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Docentes/Views/Docentes/Create.cshtml
@model Docentes.Models.Docente

@{
    ViewBag.Title = "Create";
}

@{
    Layout = null;
}



<!-- Modal -->
<div class="modal fade" id="docenteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Nuevo Docente</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">



                @using (Html.BeginForm("Create", "Docentes", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Nombres, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Inss, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Inss, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Inss, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Imagen, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="Imagen" name="Imagen" lang="es">
                                    <label class="custom-file-label" for="customFileLang">Seleccionar Archivo</label>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Guardar" class="btn btn-success" />
                            </div>
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>
</div>











@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Docentes/Views/Docentes/Delete.cshtml
@model Docentes.Models.Docente

@{
    ViewBag.Title = "Delete";
}

@{
    Layout = null;
}

<h3>Está seguro que desea eliminar este docente?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellidos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Inss)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Inss)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Imagen)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Cancelar", "Index")
        </div>
    }
</div>

Docentes/Views/Docentes/Details.cshtml
@model Docentes.Models.Docente

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Docente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellidos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Inss)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Inss)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Imagen)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Docentes/Views/Docentes/Edit.cshtml
@model Docentes.Models.Docente

@{
    ViewBag.Title = "Edit";
}

@{
    Layout = null;
}

@using (Html.BeginForm("Edit", "Docentes", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Editar Docente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Inss, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Inss, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Inss, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Imagen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="custom-file">
                    @Html.EditorFor(model => model.Imagen, new { htmlAttributes = new { @class = "custom-file-input", @type="file", @id = "Imagen", @name = "Imagen", @lang = "es" } })
                    <label class="custom-file-label" for="customFileLang">Seleccionar Archivo</label>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-warning" />
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Docentes/Views/Docentes/Index.cshtml
@model IEnumerable<Docentes.Models.Docente>

@{
    ViewBag.Title = "Index";
}

<p>
    <a href="#" class="btn btn-link" data-toggle="modal" data-target="#docenteModal">
        Nuevo Docente
    </a>
</p>

@Html.Partial("Create", new Docentes.Models.Docente())

<div class="row">

    <div class="col-6" style="min-height:70vh; max-height:70vh; overflow:scroll">
        @Html.DisplayForModel()
    </div>
    <div class="col-6" id="visualicedataviaajax">

    </div>

</div>





@section scripts {
    <script type="text/javascript">
        function loadData(url, target_id) {
            $("#" + target_id).html("<div class='text-center'><img src='/Images/loading.gif' /></div>");
            $("#" + target_id).load(url);
        }
    </script>
}

Docentes/Views/Docentes/Proyectos.cshtml
@model Docentes.Models.Docente

@{
    ViewBag.Title = "Index";
}

<p>
    <a href="/Proyectos/Create">Nuevo Proyecto</a>
</p>
<h4>Proyectos de: @Model.FullName</h4>
<div class="table-responsive-sm">
    <table class="table">
        <tr>
            <th>
                Nombre
            </th>
            <th>
                Duración
            </th>
            <th>
                Patrocinador
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.Proyectos)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Duracion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Patrocinador)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", "Proyectos", new { id = item.Id }, null) |
                    @Html.ActionLink("Delete", "Delete", "Proyectos", new { id = item.Id }, null)
                </td>
            </tr>
        }

    </table>



</div>

Docentes/Views/Docentes/Publicaciones.cshtml
@model Docentes.Models.Docente

@{
    ViewBag.Title = "Index";
}

<p>
    <a href="/Publicaciones/Create">Nueva Publicación</a>
</p>




<h4>Publicaciones de: @Model.FullName</h4>
<div class="table-responsive-sm">
    <table class="table">
        <tr>
            <th>
                Titulo
            </th>
            <th>
                Año
            </th>
            <th>
                Tipo
            </th>
            <th>
                Editorial
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.Publicaciones)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Titulo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Año)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tipo.Tipo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Editorial.Nombre)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", "Publicaciones", new { id = item.Id }, null) |
                    @Html.ActionLink("Delete", "Delete", "Publicaciones", new { id = item.Id }, null)
                </td>
            </tr>
        }

    </table>



</div>